### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by rdizzle** [DH3ALEJANDRO/brackets-open-in-browser#15]
Not really issues or bugs, but here goes.

For one, there's no retina support on the sidebar icon.
And the other thing is, that I think the icon's color stands out too much.
It always kinda catches my eye when I don't even intend to use your plugin.
I'd prefer it if it was grey like the standard ones.

Have a nice one!

**Comment by DH3ALEJANDRO** [comment]
wath?? retina??.
I promise to change the color of the icon. :tongue:

**Comment by rdizzle** [comment]
Yeah, retina. It only means that it displays two pixels instead of one on the same space.

So if you wanna add retina support, just make your icon two times the size it is now.
At the moment it looks like this. As you can see, the other icons and Brackets itself do acutally have retina support. So it'd be nice if your icon was @ 2x too.

![My Brackets side bar](http://imgur.com/ZytogDC.png)

**Comment by DH3ALEJANDRO** [comment]
:hammer: 
ok. there°°°!
