### ISSUE TITLE
Change keyboard shortcut

### ISSUE THREAD

**Issue by markhillard** [DH3ALEJANDRO/brackets-open-in-browser#16]
Just requesting a different keyboard shortcut as [Shift] + [O] will not let you type a capital "O" in any document. It appears that [Ctrl/Cmd] + [Shift] + [O] is taken and is used for the "quick open" menu, so maybe [Alt] + [Shift] + [O]?

**Comment by rdizzle** [comment]
+1

**Comment by DH3ALEJANDRO** [comment]
Ok :grinning: 

Alt-Shift-O
version 4.0.3
update.

**Comment by markhillard** [comment]
Works like a charm, thanks! Closing issue.
