### ISSUE TITLE
Not working with Brackets v. 1.11

### ISSUE THREAD

**Issue by rblinzler** [DH3ALEJANDRO/brackets-open-in-browser#27]
Open-In-Browser has not worked since I upgraded to Brackets v. 1.11. 
The open-in-browser button no longer appears. When I try to disable-enable, I get an 'Extension Error' message. When I try to unsinstall-reinstall, I get an 'Installation Failure' message.
I'm running Windows 10.

**Comment by irfandayan** [comment]
You are right, it does not work on Brackets 1.11. Any solution?

**Comment by DH3ALEJANDRO** [comment]
You could send a screenshot.
*I'm not able to find the problem.*

**Comment by rblinzler** [comment]
Sorry, I should have updated this. Open-In-Browser has been working for me. I'm on Brackets v. 1.12 and am not sure at what point it started working for me again. May have been something I had done wrong.
This issue is resolved as far as I'm concerned.

**Comment by irfandayan** [comment]
To make it work with new version of brackets, you have to completely remove the old version of brackets - It just worked that way for me. Thanks!
