### ISSUE TITLE
Duplicate icons appearing in toolbar

### ISSUE THREAD

**Issue by markhillard** [DH3ALEJANDRO/brackets-open-in-browser#9]
I love this extension since I mainly use Firefox for development work, but I found an issue where duplicate icons appear in the toolbar when selecting (clicking through) multiple files. For example, a duplicate icon appears in the toolbar each time I select an HTML file in the document tree...

![multiple-icons](https://cloud.githubusercontent.com/assets/8247756/7603325/40c6c036-f8ff-11e4-91a8-837674563c5f.png)

I fixed this by adding a line inside the `startOp()` function. It removes any instance of the icon before the `addButton()` function runs, ensuring that only one icon exists when selecting multiple files:

```js
function startOp() {
    MainViewManager.on("currentFileChange", function () {
        $("#open-notification").remove(); // remove duplicate toolbar icons
        var entry = ProjectManager.getSelectedItem().fullPath;
        var booly = ProjectManager.getSelectedItem()._name;
        if (/\.(htm|html|py|php|svg|jpg|jpeg|gif|png|ico|asp)$/i.test(booly)) {
            addButton(function () {
                NativeApp.openURLInDefaultBrowser('file:///' + entry);
            });
        } else {
            if ($("#open-notification").length) {
                $("#open-notification").remove();
            }
        }
    });
}
```

JSHint checks out and there are no console errors, but if you know of a better way to fix this I'm all ears. Figured I'd let you know.

**Comment by DH3ALEJANDRO** [comment]
there!
````
function removeButton(el) {
        if ($(el).length) {
            $(el).remove();
        }
    }
````

**Comment by markhillard** [comment]
Thanks, works like a charm!
